// @flow

/**
  * Enumeration of events, that could be
  * USER_STATE_CHANGE, HUBS_STATE_CHANGE...
  * @readonly
  * @enum {string}
  */
export const EVENTS = Object.freeze({
  USER_STATE_CHANGED: 'USER STATE CHANGED',
  HUBS_LIST_CHANGED: 'HUBS LIST CHANGED',
  HUB_SELECTED: 'HUBS LIST CHANGED',
  CLOUD_CONNECTION_STATE_CHANGED: 'CLOUD CONNECTION STATE CHANGED',
  HUB_CONNECTION_STATE_CHANGED: 'HUB CONNECTION STATE CHANGED',
});
export type EVENTSS_TYPE = $Values<typeof EVENTS>;
